[package]
name = "auth"
version = "0.1.0"
authors = ["Matthew Bentley <matthew.t.bentley@gmail.com>"]

[dependencies]
nickel = "*"
r2d2_postgres = "*"
r2d2 = "*"
openssl = "*"
uuid = "*"

[dependencies.nickel_postgres]
git = "https://github.com/matthewbentley/nickel-postgres.git"

[dependencies.cas]
git = "https://github.com/hacsoc/rust-cas.git"
